# Generated by Django 4.2.19 on 2025-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
